name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update code on PythonAnywhere
      run: |
        curl -s -X POST \
        "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/consoles/${{secrets.PA_CONSOLE_NUMBER}}/send_input/" \
        -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
        -d '{"input": "git pull origin master\n"}' \
        -H "Content-Type: application/json"

    - name: Reload PythonAnywhere Web App
      run: |
        curl -s -X POST \
        "https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/${{ secrets.PA_USERNAME }}.pythonanywhere.com/reload/" \
        -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}"
